ARG ARCH=amd64
FROM ${ARCH}/python:3.6.8-alpine

ENV DB_NAME=postgres \
DB_USER=postgres \
DB_PASS=postgres \
DB_HOST=postgres \
DB_PORT=5432 \
SMTP_HOST=smtp \
SMTP_USER=username \
SMTP_PASS=password \
SMTP_PORT=25 \
SMTP_USE_TLS=False \
DEFAULT_FROM_EMAIL=noreply@devnull.changeme \
REDIS_HOST=localhost \
REDIS_PORT=6379 \
REDIS_DB=1 \
GMAPS_API=api 

RUN mkdir /mossegada_app
COPY ./mossegada_app /mossegada_app/
WORKDIR /mossegada_app

RUN apk add --no-cache postgresql-libs jpeg-dev zlib-dev freetype-dev lcms2-dev openjpeg-dev tiff-dev tk-dev tcl-dev && apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev && pip install -r requirements.txt --no-cache-dir && apk --purge del .build-deps
