# Generated by Django 2.0.5 on 2018-06-03 21:08

from django.db import migrations


def fill_type_restaurants(apps, schema_editor):
    TypeRestaurants = apps.get_model('web_restaurants.TypeRestaurants')
    csv = open('./csv/TypeRestaurants.csv', 'r')
    csv.readline()  # Discard first line, because it's the header
    for line in csv:
        elems = line.replace('\n', '').split(',')
        TypeRestaurants(id=int(elems[0]), typeR=elems[1]).save()
    csv.close()


def fill_restaurants(apps, schema_editor):
    Restaurant = apps.get_model('web_restaurants.Restaurant')
    TypeRestaurants = apps.get_model('web_restaurants.TypeRestaurants')
    csv = open('./csv/Restaurants.csv', 'r')
    csv.readline()  # Discard first line, because it's the header
    for line in csv:
        elems = line.replace('\n', '').split(';')
        Restaurant(
            id=int(elems[0]),
            name=elems[1],
            address=elems[2],
            latitude=float(elems[3]),
            longitude=float(elems[4]),
            website=elems[5],
            phone=elems[6],
            image=elems[8],
            typeR_fk=TypeRestaurants.objects.get(id=int(elems[7]))
        ).save()
    csv.close()


class Migration(migrations.Migration):

    dependencies = [
        ('web_restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fill_type_restaurants),
        migrations.RunPython(fill_restaurants),
    ]
